#%RAML 1.0
title: Library API (Simple)
version: 1.0
baseUri: http://localhost:3000/api
mediaType: application/json

types:
  Book:
    type: object
    properties:
      id: string
      title: string
      author: string
  BookInput: 
    type: object
    properties:
      title: string
      author: string
/books:
  displayName: Books
  get:
    description: Lấy danh sách sách
    responses:
      200:
        body:
          application/json:
            type: Book[]
            example:
              - id: "1"
                title: "Lập trình Python"
                author: "Nguyen Van A"
  post:
    description: Thêm sách mới
    body:
      application/json:
        type: BookInput
    responses:
      201:
        body:
          application/json:
            type: Book
  /{id}:
    uriParameters:
      id:
        type: string
    get:
      responses:
        200:
          body:
            application/json:
              type: Book
    delete:
      responses:
        204:
          description: Đã xóa thành công