/* tslint:disable */
/* eslint-disable */
/**
 * Library API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BookInput
 */
export interface BookInput {
    /**
     * 
     * @type {string}
     * @memberof BookInput
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof BookInput
     */
    author: string;
}

/**
 * Check if a given object implements the BookInput interface.
 */
export function instanceOfBookInput(value: object): value is BookInput {
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('author' in value) || value['author'] === undefined) return false;
    return true;
}

export function BookInputFromJSON(json: any): BookInput {
    return BookInputFromJSONTyped(json, false);
}

export function BookInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): BookInput {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'],
        'author': json['author'],
    };
}

export function BookInputToJSON(json: any): BookInput {
    return BookInputToJSONTyped(json, false);
}

export function BookInputToJSONTyped(value?: BookInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'author': value['author'],
    };
}

