/* tslint:disable */
/* eslint-disable */
/**
 * Library API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Book,
  BookInput,
} from '../models/index';
import {
    BookFromJSON,
    BookToJSON,
    BookInputFromJSON,
    BookInputToJSON,
} from '../models/index';

export interface BooksIdDeleteRequest {
    id: string;
}

export interface BooksIdGetRequest {
    id: string;
}

export interface BooksIdPutRequest {
    id: string;
    bookInput: BookInput;
}

export interface BooksPostRequest {
    bookInput: BookInput;
}

/**
 * 
 */
export class DefaultApi extends runtime.BaseAPI {

    /**
     * Creates request options for booksGet without sending the request
     */
    async booksGetRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/books`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Lấy danh sách sách
     */
    async booksGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Book>>> {
        const requestOptions = await this.booksGetRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(BookFromJSON));
    }

    /**
     * Lấy danh sách sách
     */
    async booksGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Book>> {
        const response = await this.booksGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for booksIdDelete without sending the request
     */
    async booksIdDeleteRequestOpts(requestParameters: BooksIdDeleteRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling booksIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/books/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Xóa sách
     */
    async booksIdDeleteRaw(requestParameters: BooksIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.booksIdDeleteRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Xóa sách
     */
    async booksIdDelete(requestParameters: BooksIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.booksIdDeleteRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for booksIdGet without sending the request
     */
    async booksIdGetRequestOpts(requestParameters: BooksIdGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling booksIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/books/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Lấy chi tiết sách
     */
    async booksIdGetRaw(requestParameters: BooksIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Book>> {
        const requestOptions = await this.booksIdGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BookFromJSON(jsonValue));
    }

    /**
     * Lấy chi tiết sách
     */
    async booksIdGet(requestParameters: BooksIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Book> {
        const response = await this.booksIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for booksIdPut without sending the request
     */
    async booksIdPutRequestOpts(requestParameters: BooksIdPutRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling booksIdPut().'
            );
        }

        if (requestParameters['bookInput'] == null) {
            throw new runtime.RequiredError(
                'bookInput',
                'Required parameter "bookInput" was null or undefined when calling booksIdPut().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/books/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: BookInputToJSON(requestParameters['bookInput']),
        };
    }

    /**
     * Cập nhật sách
     */
    async booksIdPutRaw(requestParameters: BooksIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Book>> {
        const requestOptions = await this.booksIdPutRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BookFromJSON(jsonValue));
    }

    /**
     * Cập nhật sách
     */
    async booksIdPut(requestParameters: BooksIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Book> {
        const response = await this.booksIdPutRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for booksPost without sending the request
     */
    async booksPostRequestOpts(requestParameters: BooksPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['bookInput'] == null) {
            throw new runtime.RequiredError(
                'bookInput',
                'Required parameter "bookInput" was null or undefined when calling booksPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/books`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: BookInputToJSON(requestParameters['bookInput']),
        };
    }

    /**
     * Thêm sách
     */
    async booksPostRaw(requestParameters: BooksPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Book>> {
        const requestOptions = await this.booksPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BookFromJSON(jsonValue));
    }

    /**
     * Thêm sách
     */
    async booksPost(requestParameters: BooksPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Book> {
        const response = await this.booksPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
