from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.category import Category
from openapi_server import util

from openapi_server.models.category import Category  # noqa: E501

class ListCategories200Response(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, data=None):  # noqa: E501
        """ListCategories200Response - a model defined in OpenAPI

        :param data: The data of this ListCategories200Response.  # noqa: E501
        :type data: List[Category]
        """
        self.openapi_types = {
            'data': List[Category]
        }

        self.attribute_map = {
            'data': 'data'
        }

        self._data = data

    @classmethod
    def from_dict(cls, dikt) -> 'ListCategories200Response':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The listCategories_200_response of this ListCategories200Response.  # noqa: E501
        :rtype: ListCategories200Response
        """
        return util.deserialize_model(dikt, cls)

    @property
    def data(self) -> List[Category]:
        """Gets the data of this ListCategories200Response.


        :return: The data of this ListCategories200Response.
        :rtype: List[Category]
        """
        return self._data

    @data.setter
    def data(self, data: List[Category]):
        """Sets the data of this ListCategories200Response.


        :param data: The data of this ListCategories200Response.
        :type data: List[Category]
        """

        self._data = data
