from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.product import Product
from openapi_server import util

from openapi_server.models.product import Product  # noqa: E501

class ProductListResponse(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, data=None):  # noqa: E501
        """ProductListResponse - a model defined in OpenAPI

        :param data: The data of this ProductListResponse.  # noqa: E501
        :type data: List[Product]
        """
        self.openapi_types = {
            'data': List[Product]
        }

        self.attribute_map = {
            'data': 'data'
        }

        self._data = data

    @classmethod
    def from_dict(cls, dikt) -> 'ProductListResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ProductListResponse of this ProductListResponse.  # noqa: E501
        :rtype: ProductListResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def data(self) -> List[Product]:
        """Gets the data of this ProductListResponse.


        :return: The data of this ProductListResponse.
        :rtype: List[Product]
        """
        return self._data

    @data.setter
    def data(self, data: List[Product]):
        """Sets the data of this ProductListResponse.


        :param data: The data of this ProductListResponse.
        :type data: List[Product]
        """

        self._data = data
