from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class ProductCreate(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, name=None, description=None, price=None, sku=None, category_id=None, stock_quantity=0, status='draft'):  # noqa: E501
        """ProductCreate - a model defined in OpenAPI

        :param name: The name of this ProductCreate.  # noqa: E501
        :type name: str
        :param description: The description of this ProductCreate.  # noqa: E501
        :type description: str
        :param price: The price of this ProductCreate.  # noqa: E501
        :type price: float
        :param sku: The sku of this ProductCreate.  # noqa: E501
        :type sku: str
        :param category_id: The category_id of this ProductCreate.  # noqa: E501
        :type category_id: int
        :param stock_quantity: The stock_quantity of this ProductCreate.  # noqa: E501
        :type stock_quantity: int
        :param status: The status of this ProductCreate.  # noqa: E501
        :type status: str
        """
        self.openapi_types = {
            'name': str,
            'description': str,
            'price': float,
            'sku': str,
            'category_id': int,
            'stock_quantity': int,
            'status': str
        }

        self.attribute_map = {
            'name': 'name',
            'description': 'description',
            'price': 'price',
            'sku': 'sku',
            'category_id': 'category_id',
            'stock_quantity': 'stock_quantity',
            'status': 'status'
        }

        self._name = name
        self._description = description
        self._price = price
        self._sku = sku
        self._category_id = category_id
        self._stock_quantity = stock_quantity
        self._status = status

    @classmethod
    def from_dict(cls, dikt) -> 'ProductCreate':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ProductCreate of this ProductCreate.  # noqa: E501
        :rtype: ProductCreate
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self) -> str:
        """Gets the name of this ProductCreate.


        :return: The name of this ProductCreate.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this ProductCreate.


        :param name: The name of this ProductCreate.
        :type name: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def description(self) -> str:
        """Gets the description of this ProductCreate.


        :return: The description of this ProductCreate.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description: str):
        """Sets the description of this ProductCreate.


        :param description: The description of this ProductCreate.
        :type description: str
        """

        self._description = description

    @property
    def price(self) -> float:
        """Gets the price of this ProductCreate.


        :return: The price of this ProductCreate.
        :rtype: float
        """
        return self._price

    @price.setter
    def price(self, price: float):
        """Sets the price of this ProductCreate.


        :param price: The price of this ProductCreate.
        :type price: float
        """
        if price is None:
            raise ValueError("Invalid value for `price`, must not be `None`")  # noqa: E501

        self._price = price

    @property
    def sku(self) -> str:
        """Gets the sku of this ProductCreate.


        :return: The sku of this ProductCreate.
        :rtype: str
        """
        return self._sku

    @sku.setter
    def sku(self, sku: str):
        """Sets the sku of this ProductCreate.


        :param sku: The sku of this ProductCreate.
        :type sku: str
        """
        if sku is None:
            raise ValueError("Invalid value for `sku`, must not be `None`")  # noqa: E501

        self._sku = sku

    @property
    def category_id(self) -> int:
        """Gets the category_id of this ProductCreate.


        :return: The category_id of this ProductCreate.
        :rtype: int
        """
        return self._category_id

    @category_id.setter
    def category_id(self, category_id: int):
        """Sets the category_id of this ProductCreate.


        :param category_id: The category_id of this ProductCreate.
        :type category_id: int
        """
        if category_id is None:
            raise ValueError("Invalid value for `category_id`, must not be `None`")  # noqa: E501

        self._category_id = category_id

    @property
    def stock_quantity(self) -> int:
        """Gets the stock_quantity of this ProductCreate.


        :return: The stock_quantity of this ProductCreate.
        :rtype: int
        """
        return self._stock_quantity

    @stock_quantity.setter
    def stock_quantity(self, stock_quantity: int):
        """Sets the stock_quantity of this ProductCreate.


        :param stock_quantity: The stock_quantity of this ProductCreate.
        :type stock_quantity: int
        """

        self._stock_quantity = stock_quantity

    @property
    def status(self) -> str:
        """Gets the status of this ProductCreate.


        :return: The status of this ProductCreate.
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status: str):
        """Sets the status of this ProductCreate.


        :param status: The status of this ProductCreate.
        :type status: str
        """

        self._status = status
