from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.product import Product
from openapi_server import util

from openapi_server.models.product import Product  # noqa: E501

class ProductResponse(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, data=None):  # noqa: E501
        """ProductResponse - a model defined in OpenAPI

        :param data: The data of this ProductResponse.  # noqa: E501
        :type data: Product
        """
        self.openapi_types = {
            'data': Product
        }

        self.attribute_map = {
            'data': 'data'
        }

        self._data = data

    @classmethod
    def from_dict(cls, dikt) -> 'ProductResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ProductResponse of this ProductResponse.  # noqa: E501
        :rtype: ProductResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def data(self) -> Product:
        """Gets the data of this ProductResponse.


        :return: The data of this ProductResponse.
        :rtype: Product
        """
        return self._data

    @data.setter
    def data(self, data: Product):
        """Sets the data of this ProductResponse.


        :param data: The data of this ProductResponse.
        :type data: Product
        """

        self._data = data
