from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class ProductPatch(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, name=None, description=None, price=None, stock_quantity=None):  # noqa: E501
        """ProductPatch - a model defined in OpenAPI

        :param name: The name of this ProductPatch.  # noqa: E501
        :type name: str
        :param description: The description of this ProductPatch.  # noqa: E501
        :type description: str
        :param price: The price of this ProductPatch.  # noqa: E501
        :type price: float
        :param stock_quantity: The stock_quantity of this ProductPatch.  # noqa: E501
        :type stock_quantity: int
        """
        self.openapi_types = {
            'name': str,
            'description': str,
            'price': float,
            'stock_quantity': int
        }

        self.attribute_map = {
            'name': 'name',
            'description': 'description',
            'price': 'price',
            'stock_quantity': 'stock_quantity'
        }

        self._name = name
        self._description = description
        self._price = price
        self._stock_quantity = stock_quantity

    @classmethod
    def from_dict(cls, dikt) -> 'ProductPatch':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ProductPatch of this ProductPatch.  # noqa: E501
        :rtype: ProductPatch
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self) -> str:
        """Gets the name of this ProductPatch.


        :return: The name of this ProductPatch.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this ProductPatch.


        :param name: The name of this ProductPatch.
        :type name: str
        """

        self._name = name

    @property
    def description(self) -> str:
        """Gets the description of this ProductPatch.


        :return: The description of this ProductPatch.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description: str):
        """Sets the description of this ProductPatch.


        :param description: The description of this ProductPatch.
        :type description: str
        """

        self._description = description

    @property
    def price(self) -> float:
        """Gets the price of this ProductPatch.


        :return: The price of this ProductPatch.
        :rtype: float
        """
        return self._price

    @price.setter
    def price(self, price: float):
        """Sets the price of this ProductPatch.


        :param price: The price of this ProductPatch.
        :type price: float
        """

        self._price = price

    @property
    def stock_quantity(self) -> int:
        """Gets the stock_quantity of this ProductPatch.


        :return: The stock_quantity of this ProductPatch.
        :rtype: int
        """
        return self._stock_quantity

    @stock_quantity.setter
    def stock_quantity(self, stock_quantity: int):
        """Sets the stock_quantity of this ProductPatch.


        :param stock_quantity: The stock_quantity of this ProductPatch.
        :type stock_quantity: int
        """

        self._stock_quantity = stock_quantity
