from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class StockResponse(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, product_id=None, previous_quantity=None, current_quantity=None, updated_at=None):  # noqa: E501
        """StockResponse - a model defined in OpenAPI

        :param product_id: The product_id of this StockResponse.  # noqa: E501
        :type product_id: int
        :param previous_quantity: The previous_quantity of this StockResponse.  # noqa: E501
        :type previous_quantity: int
        :param current_quantity: The current_quantity of this StockResponse.  # noqa: E501
        :type current_quantity: int
        :param updated_at: The updated_at of this StockResponse.  # noqa: E501
        :type updated_at: datetime
        """
        self.openapi_types = {
            'product_id': int,
            'previous_quantity': int,
            'current_quantity': int,
            'updated_at': datetime
        }

        self.attribute_map = {
            'product_id': 'product_id',
            'previous_quantity': 'previous_quantity',
            'current_quantity': 'current_quantity',
            'updated_at': 'updated_at'
        }

        self._product_id = product_id
        self._previous_quantity = previous_quantity
        self._current_quantity = current_quantity
        self._updated_at = updated_at

    @classmethod
    def from_dict(cls, dikt) -> 'StockResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The StockResponse of this StockResponse.  # noqa: E501
        :rtype: StockResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def product_id(self) -> int:
        """Gets the product_id of this StockResponse.


        :return: The product_id of this StockResponse.
        :rtype: int
        """
        return self._product_id

    @product_id.setter
    def product_id(self, product_id: int):
        """Sets the product_id of this StockResponse.


        :param product_id: The product_id of this StockResponse.
        :type product_id: int
        """

        self._product_id = product_id

    @property
    def previous_quantity(self) -> int:
        """Gets the previous_quantity of this StockResponse.


        :return: The previous_quantity of this StockResponse.
        :rtype: int
        """
        return self._previous_quantity

    @previous_quantity.setter
    def previous_quantity(self, previous_quantity: int):
        """Sets the previous_quantity of this StockResponse.


        :param previous_quantity: The previous_quantity of this StockResponse.
        :type previous_quantity: int
        """

        self._previous_quantity = previous_quantity

    @property
    def current_quantity(self) -> int:
        """Gets the current_quantity of this StockResponse.


        :return: The current_quantity of this StockResponse.
        :rtype: int
        """
        return self._current_quantity

    @current_quantity.setter
    def current_quantity(self, current_quantity: int):
        """Sets the current_quantity of this StockResponse.


        :param current_quantity: The current_quantity of this StockResponse.
        :type current_quantity: int
        """

        self._current_quantity = current_quantity

    @property
    def updated_at(self) -> datetime:
        """Gets the updated_at of this StockResponse.


        :return: The updated_at of this StockResponse.
        :rtype: datetime
        """
        return self._updated_at

    @updated_at.setter
    def updated_at(self, updated_at: datetime):
        """Sets the updated_at of this StockResponse.


        :param updated_at: The updated_at of this StockResponse.
        :type updated_at: datetime
        """

        self._updated_at = updated_at
