from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class StockUpdate(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, action=None, quantity=None):  # noqa: E501
        """StockUpdate - a model defined in OpenAPI

        :param action: The action of this StockUpdate.  # noqa: E501
        :type action: str
        :param quantity: The quantity of this StockUpdate.  # noqa: E501
        :type quantity: int
        """
        self.openapi_types = {
            'action': str,
            'quantity': int
        }

        self.attribute_map = {
            'action': 'action',
            'quantity': 'quantity'
        }

        self._action = action
        self._quantity = quantity

    @classmethod
    def from_dict(cls, dikt) -> 'StockUpdate':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The StockUpdate of this StockUpdate.  # noqa: E501
        :rtype: StockUpdate
        """
        return util.deserialize_model(dikt, cls)

    @property
    def action(self) -> str:
        """Gets the action of this StockUpdate.


        :return: The action of this StockUpdate.
        :rtype: str
        """
        return self._action

    @action.setter
    def action(self, action: str):
        """Sets the action of this StockUpdate.


        :param action: The action of this StockUpdate.
        :type action: str
        """
        allowed_values = ["set", "increment", "decrement"]  # noqa: E501
        if action not in allowed_values:
            raise ValueError(
                "Invalid value for `action` ({0}), must be one of {1}"
                .format(action, allowed_values)
            )

        self._action = action

    @property
    def quantity(self) -> int:
        """Gets the quantity of this StockUpdate.


        :return: The quantity of this StockUpdate.
        :rtype: int
        """
        return self._quantity

    @quantity.setter
    def quantity(self, quantity: int):
        """Sets the quantity of this StockUpdate.


        :param quantity: The quantity of this StockUpdate.
        :type quantity: int
        """
        if quantity is None:
            raise ValueError("Invalid value for `quantity`, must not be `None`")  # noqa: E501

        self._quantity = quantity
